# Generated by Django 5.0 on 2024-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_clubprofile_createclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclub',
            name='clubname',
            field=models.CharField(max_length=100),
        ),
    ]
