# Generated by Django 5.0 on 2024-04-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_createclub_clubname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createclub',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='createclub',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('gaming', 'Gaming'), ('technology', 'Technology'), ('society', 'Society'), ('programming', 'Programming'), ('art', 'Art')], max_length=100),
        ),
        migrations.AlterField(
            model_name='createclub',
            name='clubmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createclub',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
