# Generated by Django 4.2.7 on 2024-04-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_createclub_id_user_alter_createclub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='clubmanager',
        ),
        migrations.RemoveField(
            model_name='post',
            name='clubvicemanager',
        ),
        migrations.RemoveField(
            model_name='post',
            name='phonenumber1',
        ),
    ]
