# Generated by Django 5.0 on 2024-04-25 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_eventactivity_clubname_alter_post_clubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
