# Generated by Django 5.0 on 2024-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_eventactivity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactivity',
            name='clubname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clubname',
            field=models.CharField(max_length=100),
        ),
    ]
