# Generated by Django 5.0 on 2024-04-25 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_eventactivity_clubname_alter_eventactivity_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventactivity',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='post',
            name='clubmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_managed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventactivity',
            name='clubmanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
