# Generated by Django 5.0 on 2024-04-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_eventactivity_approved_post_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='clubmanager',
        ),
    ]
