# Generated by Django 5.0 on 2024-04-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_post_clubmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventactivity',
            name='clubmanager',
        ),
    ]
