# Generated by Django 5.0 on 2024-04-27 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_eventactivity_clubmanager_post_clubmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclub',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
