# Generated by Django 5.0 on 2024-04-28 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_createclub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('clubname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject', to='pages.createclub')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
