# Generated by Django 5.0 on 2024-04-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rejections_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejections',
            name='clubname',
        ),
    ]
