# Generated by Django 4.2.7 on 2024-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_rejections_clubname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createclub',
            name='profileimg2',
        ),
        migrations.AddField(
            model_name='createclub',
            name='bgimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='bg_image'),
        ),
        migrations.AlterField(
            model_name='createclub',
            name='phonenumber1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='createclub',
            name='phonenumber2',
            field=models.CharField(max_length=300),
        ),
    ]
