# Generated by Django 5.0 on 2024-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_createclub_profileimg2_createclub_bgimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createclub',
            name='club_achievement1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createclub',
            name='club_achievement2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createclub',
            name='club_achievement3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createclub',
            name='club_achievement4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createclub',
            name='club_achievement5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='createclub',
            name='number_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
