# Generated by Django 5.0 on 2024-04-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_editeventactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editeventactivity',
            name='clubname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_Edit', to='pages.createclub'),
        ),
    ]
