# Generated by Django 5.0 on 2024-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_editeventactivity_clubname'),
    ]

    operations = [
        migrations.AddField(
            model_name='editeventactivity',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejected'),
        ),
        migrations.AddField(
            model_name='eventactivity',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejected'),
        ),
        migrations.AddField(
            model_name='post',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejected'),
        ),
    ]
