# Generated by Django 5.0 on 2024-04-30 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_editeventactivity_rejected_eventactivity_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejections',
            name='event_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason', to='pages.eventactivity'),
        ),
        migrations.AddField(
            model_name='rejections',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason', to='pages.post'),
        ),
    ]
