# Generated by Django 5.0 on 2024-05-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_rejections_event_activity_rejections_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventactivity',
            name='edit_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_event', to='pages.editeventactivity'),
        ),
    ]
