# Generated by Django 5.0 on 2024-05-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_editpost_post_edit_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejections',
            name='edit_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason', to='pages.editpost'),
        ),
    ]
